# .github/workflows/deploy.yml
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NODE_OPTIONS=--openssl-legacy-provider
            cd ~/apps/erp-web
            git pull origin master
            npm install --omit=dev
            npm run build
            pm2 reload erp-web
